name: Build Toss PC (Windows)

on:
  push:
    branches: [ main ]

jobs:
  build-tauri:
    permissions:
      contents: write    # <--- INI SURAT IZINNYA BIAR BISA UPLOAD .EXE
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        working-directory: ./toss-pc
        run: npm install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./toss-pc
          tagName: v__VERSION__
          releaseName: 'Toss PC v__VERSION__'
          releaseDraft: true